services:
    api01: &api
        build: .
        hostname: api01
        environment:
            - DATABASE_URL=postgres://admin:123@db:5432/rinha
            - RUST_LOG=info
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.5" # 1
                    memory: "75MB" # 150MB
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s

    api02:
        <<: *api
        hostname: api02

    nginx:
        image: nginx:alpine
        ports:
            - "9999:9999"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

        depends_on:
            - api01
            - api02
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: "200MB"

    db:
        image: postgres:17-alpine
        hostname: db
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=admin
            - POSTGRES_DB=rinha
            - POSTGRES_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
        volumes:
            - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
            - postgres_data:/var/lib/postgresql/data
        command: |
            postgres
            -c max_connections=200
            -c shared_buffers=128MB
            -c effective_cache_size=256MB
            -c maintenance_work_mem=64MB
            -c checkpoint_completion_target=0.9
            -c wal_buffers=16MB
            -c default_statistics_target=100
            -c random_page_cost=1.1
            -c effective_io_concurrency=200
            -c work_mem=4MB
            -c min_wal_size=1GB
            -c max_wal_size=4GB
            -c max_worker_processes=8
            -c max_parallel_workers_per_gather=4
            -c max_parallel_workers=8
            -c max_parallel_maintenance_workers=4
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: "200MB"

volumes:
    postgres_data:

networks:
    default:
        driver: bridge
        name: rinha-backend-2024q1
