services:
    api01: &api
        build: .
        hostname: api01
        restart: unless-stopped
        environment:
            - DATABASE_URL=sqlite:///shared/rinha.db
            - RUST_LOG=info
        volumes:
            - shared_data:/shared:rw
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "200MB"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s

    api02:
        <<: *api
        hostname: api02

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9999:9999"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "150MB"

volumes:
    shared_data:

networks:
    default:
        driver: bridge
        name: rinha-backend-2024q1
